schema_version: "1.0"
mcp_name: "Colombian Law MCP"
jurisdiction: "CO"

sources:
  - name: "Función Pública"
    authority: "Función Pública"
    official_portal: "https://www.funcionpublica.gov.co"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "weekly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Open Data"
      url: "https://www.funcionpublica.gov.co"
      summary: "Official legislative texts are public domain"
    coverage:
      scope: "Data protection, cybersecurity, e-commerce, criminal law cyber provisions"
      limitations: "AI-generated seed data; full official ingestion pending"
    languages:
      - "es"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
