schema_version: "1.0"
mcp_name: "Colombian Law MCP"
jurisdiction: "CO"

sources:
  - name: "Gestor Normativo - Función Pública"
    authority: "Departamento Administrativo de la Función Pública (DAFP)"
    official_portal: "https://www.funcionpublica.gov.co/eva/gestornormativo/"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://www.funcionpublica.gov.co"
      summary: "Legislation is publicly accessible on a government portal; portal terms apply."
    coverage:
      scope: "Leyes y decretos nacionales publicados en Gestor Normativo, incluyendo normas de TIC, protección de datos, transparencia y comercio electrónico."
      limitations: "El portal advierte que los datos son informativos; la vigencia oficial debe confirmarse con Diario Oficial y entidades competentes."
    languages:
      - "es"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
